# Generated by Django 4.1 on 2022-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='total',
            field=models.IntegerField(default=516),
        ),
        migrations.AlterField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.JSONField(default=[48, 42, 30, 24, 42, 24, 36, 42, 42, 48, 36, 42, 24, 36], null=True),
        ),
    ]
